### ISSUE TITLE
Abandoned dependencies

### ISSUE THREAD

**Issue by UOCecalero** [semyonchetvertnyh/laravel-apn-notification-channel#12]
When I installed the package it throws me this warning:

  - Installing psr/cache (1.0.1) Downloading: 100%         
  - Installing fgrosse/phpasn1 (v2.1.1) Downloading: 100%         
  - Installing mdanter/ecc (v0.5.2) Downloading: 100%         
  - Installing beberlei/assert (v2.9.9) Downloading: 100%         
  - Installing spomky-labs/php-aes-gcm (v1.2.1) Downloading: 100%         
  - Installing spomky-labs/aes-key-wrap (v4.0.1) Downloading: 100%         
  - Installing spomky-labs/base64url (v1.0.2) Downloading: 100%         
  - Installing spomky-labs/jose (v7.1.0) Downloading: 100%         
  - Installing edamov/pushok (0.4.3) Downloading: 100%         
  - Installing semyonchetvertnyh/laravel-apn-notification-channel (v0.1.5) Downloading: 100%   

      
fgrosse/phpasn1 suggests installing php-curl (For loading OID information from the web if they have not bee defined statically)
spomky-labs/php-aes-gcm suggests installing ext-crypto (Highly recommended for better performance.)
spomky-labs/jose suggests installing ext-crypto (Highly recommended when you use AES GCM based algorithms.)
spomky-labs/jose suggests installing ext-ed25519 (For EdDSA with Ed25519 curves support.)
spomky-labs/jose suggests installing ext-curve25519 (For EdDSA with X25519 curves support.)
**Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.**

**Comment by semyonchetvertnyh** [comment]
Update please to [v1.0.0](https://github.com/semyonchetvertnyh/laravel-apn-notification-channel/releases/tag/v1.0.0). All dependencies in this version are actual to the moment.
