### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by asvechkar** [semyonchetvertnyh/laravel-apn-notification-channel#20]
ErrorException(code: 0): Undefined offset: 1 at /var/www/stage/releases/58/vendor/edamov/pushok/src/Client.php:122

Установлен Laravel 5.7
semyonchetvertnyh/laravel-apn-notification-channel 1.5

**Comment by asvechkar** [comment]
Поставил версию 0.1.3, ошибка сохранилась.

**Comment by asvechkar** [comment]
В /var/www/stage/releases/58/vendor/edamov/pushok/src/Client.php:122 переменная $result возвращает пустую строку, отсюда ошибка при попытке разбить строку на массив

**Comment by pliasun** [comment]
curl -I --http2 https://www.cloudflare.com/

**Comment by semyonchetvertnyh** [comment]
Обновитесь, пожалуйста, до версии [v1.0.0](https://github.com/semyonchetvertnyh/laravel-apn-notification-channel/releases/tag/v1.0.0).
