### ISSUE TITLE
Subtitle not appearing on notification

### ISSUE THREAD

**Issue by antonioreyna** [semyonchetvertnyh/laravel-apn-notification-channel#5]
hello, the subtitle is not showing in the device notification.

**Comment by semyonchetvertnyh** [comment]
Hello!

It's will be easier to investigate it, if you provide the example of code that sends your notification.

**Comment by antonioreyna** [comment]
for this i think its related to pushok, as it is not taking the latest from the composer. can you please set the latest pushok in this project?

**Comment by semyonchetvertnyh** [comment]
Give me some time please. I'll be checking that it'll be not a breaking change, and if not - I will make a new version of package.

**Comment by antonioreyna** [comment]
sure, thank you.

Also looks like the new pushok library removes the "spomky-labs/jose" which is now unsupported or deprecated or something like that.

**Comment by semyonchetvertnyh** [comment]
If you want you can make a PR to increase a version of pushok. I will just test your PR and merge it if it's ok.

**Comment by semyonchetvertnyh** [comment]
I'm closing the issue, because it should be fixed in [v1.0.0](https://github.com/semyonchetvertnyh/laravel-apn-notification-channel/releases/tag/v1.0.0).
